In [1]:
import sys

sys.path.append("..")

from common.metrics import metrics
from common.preprocessing import preprocessing_cn7
from common.train_test_split import split_data
from common.model_composition import model_composition

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 데이터 불러오기
train_cn7 = pd.read_csv(r"C:\Users\Administrator\Desktop\kamp\1. 사출성형기 AI 데이터셋\1. 사출성형기 AI 데이터셋\moldset_labeled_cn7.csv")

In [3]:
X_cn7, y_cn7 = preprocessing_cn7(train_cn7)

print("X shape:", X_cn7.shape)
print("y shape:", y_cn7.shape)

X shape: (1211, 23)
y shape: (1211,)

In [4]:
X_train_cn7, X_test_cn7, y_train_cn7, y_test_cn7 = split_data(
    X_cn7,
    y_cn7
)

In [5]:
from common.basic_model import svm_classifier
from common.metrics import metrics

model = svm_classifier(
    X_train_cn7,
    y_train_cn7
)

y_pred = model.predict(X_test_cn7)
y_prob = model.predict_proba(X_test_cn7)[:, 1]

print("[CN7 SVM Baseline]")
metrics(y_test_cn7, y_pred, y_prob)

[CN7 SVM Baseline]
Accuracy : 0.9876543209876543
Precision: 0.0
Recall   : 0.0
F1       : 0.0
PR-AUC   : 0.08370113493064313

Confusion Matrix

c:\Users\Administrator\Desktop\kamp\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

               Pred Normal  Pred Defect
Actual Normal          240            0
Actual Defect            3            0

In [6]:
model = svm_classifier(
    X_train_cn7,
    y_train_cn7,
    class_weight="balanced"
)

y_pred = model.predict(X_test_cn7)
y_prob = model.predict_proba(X_test_cn7)[:, 1]

print("[CN7 SVM Class Weight]")
metrics(y_test_cn7, y_pred, y_prob)

[CN7 SVM Class Weight]
Accuracy : 0.9794238683127572
Precision: 0.0
Recall   : 0.0
F1       : 0.0
PR-AUC   : 0.12654625068418174

Confusion Matrix

c:\Users\Administrator\Desktop\kamp\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

               Pred Normal  Pred Defect
Actual Normal          238            2
Actual Defect            3            0

### SVM Balanced

In [7]:
model = svm_classifier(
    X_train_cn7,
    y_train_cn7,
    class_weight="balanced"
)

y_pred = model.predict(X_test_cn7)
y_prob = model.predict_proba(X_test_cn7)[:, 1]

print("[CN7 SVM Class Weight]")
metrics(y_test_cn7, y_pred, y_prob)

[CN7 SVM Class Weight]
Accuracy : 0.9794238683127572
Precision: 0.0
Recall   : 0.0
F1       : 0.0
PR-AUC   : 0.12654625068418174

Confusion Matrix

c:\Users\Administrator\Desktop\kamp\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

               Pred Normal  Pred Defect
Actual Normal          238            2
Actual Defect            3            0